[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "package"
version = "0.1.0"
description = "Example application demonstrating how to write packages containing multiple actors"
keywords = ["basic", "std"]

[dependencies]
log = "0.4"
env_logger = "0.8"
drogue-device = { path = "../../../device", features = ["log", "std"] }
embassy = { version = "0.1.0", default-features = false, features = ["std"] }