[package]
edition = "2021"
name = "iot01a-wifi"
version = "0.1.0"
resolver = "2"
description = "STM32 IoT Discovery board (iot01a) reporting sensor data using WiFi"
keywords = ["wifi", "hts221", "stm32l4", "networking", "iot", "stm32", "cloud", "ota"]

[dependencies]
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"], optional = true }
panic-reset = { version = "0.1.1", optional = true }

drogue-device = { path = "../../../../device", default-features = false, features = ["time"] }
static_cell = "1"
cortex-m-rt = "0.7.3"
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.4", default-features = false, features = ["heapless"] }
heapless = "0.7"

critical-section = "0.2.5"
rand_core = { version = "0.6.2", default-features = false }
embedded-nal-async = "0.3.0"
disco-iot01a = { path = "../../../../boards/disco-iot01a" }
reqwless = { version = "0.3", default-features = false, features = ["defmt"] }
cfg-if = "1.0.0"
embedded-io = "0.4"
hts221-async = { version = "0.2.0", features = ["defmt"] }

atomic-polyfill = "1"
embassy-executor = { version = "0.1.0", default-features = false, features=["nightly", "integrated-timers"] }
embassy-time = { version = "0.1.0", default-features = false }
embassy-stm32 = { version = "0.1.0", default-features = false, features = ["time-driver-any", "unstable-traits"] }
embassy-futures = { version = "0.1.0" }

embassy-boot-stm32 = { version = "0.1.0", default-features = false }

[features]
default = ["panic-reset", "l475e"]
debug = [
    "panic-probe",
    "drogue-device/defmt",
    "embassy-executor/defmt",
    #"embassy-stm32/defmt",
    #"embassy-boot-stm32/defmt",
    "disco-iot01a/defmt",
    "reqwless/defmt",
    "hts221-async/defmt",
]
l4s5i = ["disco-iot01a/l4s5i"]
l475e = ["disco-iot01a/l475e"]
