== microbit-esp8266 drogue-device example

This example application runs out of the box on the BBC micro:bit v2.0.
It relies on a ESP8266 breakout module flashed with AT firmware. The micro:bit communicates with the
ESP8266 using UART.

=== Prerequisites

==== Hardware

* BBC micro:bit v2.0
* ESP8266 module with AT-command firmware version 1.7.x or newer.

==== Software

* To build the example, you need to have link:https://rustup.rs/[Rust Nightly].
* To flash the example on the device, you need `probe-run` installed (`cargo install probe-run`).
* A TCP server that accepts connections and echoes input back to the client. A simple way to run it is to use link:ncat[https://nmap.org/ncat/guide/ncat-simple-services.html]: `ncat -l 12345 --keep-open --exec "/bin/cat"`


=== Configuring

To use this example, you need to edit the HOST and PORT constants in `src/main.rs`. You
also need to store your WiFi access point ssid in `config/wifi.ssid.txt` and pre-shared key in
`config/wifi.password.txt`.

=== Building

Make sure you have the correct target architecture supported in rust:

....
rustup target add thumbv7em-none-eabihf
....

To build the firmware:

....
cargo build --release
....

=== Running

First, start the TCP server in a terminal:

....
ncat -l 12345 --keep-open --exec "/bin/cat"
....

Next, we need to flash the firmware on the device. Flashing the firmware uses `probe-run` which auto-detects the probe connected to your device. The following command will build and flash the firmware and open the debugger console so you can see the console debug output:

....
cargo +nightly run --release
....

If you’re experiencing problems, try setting the `VID:PID` values to that of your probe (you can find that from lsusb once your board is powered).

....
cargo +nightly run --release -- --probe <VID>:<PID>
....