== microbit-esp8266 drogue-device example

This example application runs out of the box on the BBC micro:bit v2.0.
It relies on a ESP8266 breakout module flashed with AT firmware. The micro:bit communicates with the
ESP8266 using UART.

=== Prerequisites

==== Hardware

* BBC micro:bit v2.0
* ESP8266 module with AT-command firmware version 1.7.x or newer.

==== Software

To build and flash the example, you need to have
link:https://rustup.rs/[Rust Nightly]. In practice
you can use whatever tool you want to flash the device, but this guide
will assume that `probe-run` is used (`cargo install probe-run`).

=== Configuring

To use this example, you need to edit the HOST and PORT constants in `src/main.rs`. You
also need to store your WiFi access point ssid in `config/wifi.ssid.txt` and pre-shared key in
`config/wifi.password.txt`.

=== Building

Make sure you have the correct target architecture supported in rust:

....
rustup target add thumbv7em-none-eabihf
....

To build the firmware:

....
cargo build --release
....

=== Flashing

Flashing the firmware uses `probe-run` which auto-detects the probe connected to your device. 
The following command will build and flash the firmware and open the
debugger console so you can see the console debug output.

....
cargo +nightly run --release
....

If you’re experiencing problems, try setting the `VID:PID` values to
that of your probe (you can find that from lsusb once your board is
powered).

....
cargo +nightly run --release -- --probe <VID>:<PID>
....