== STM32 IOT01A example

This example application runs out of the box on the STM32 IOT01A development kits. It features a bootloader to provide firmware update capabilities.
It uses the on board peripherals such as WiFi and the temperature sensor to send data to an HTTP endpoint such as Drogue Cloud, and to retrieve firmware updates.

NOTE: There are multiple variants of this kit, so the example must be compiled and run using feature flags.

The example can operate using plain TCP, or using TLS by enabling the `tls` feature flag.

=== Prerequisites

==== Hardware

* STM32 IOT01A development kit

==== Software

* To build the example, you need to have link:https://rustup.rs/[rustup].
* To flash the example on the device, you need `probe-run` installed (`cargo install probe-run`).
* A Drogue Cloud instance. See link:https://github.com/drogue-iot/drogue-cloud/[drogue-cloud] for how to run that, or use the link:https://sandbox.drogue.cloud/[sandbox] (requires TLS).


=== Flashing the bootloader

To flash the bootloader for a given chip:

....
cargo flash --manifest-path ../bootloader/Cargo.toml --release --features b-l4s5i-iot01a --no-default-features --chip STM32L4S5VI
....

If you have the B-475E-IOT01A board, use the following parameters:

....
cargo flash --manifest-path ../bootloader/Cargo.toml --release --features b-l475e-iot01a --no-default-features --chip STM32L475VG
....

=== Configuring

Credentials for your local WiFi network will come from these entries in `~/.drogue/config.toml`:

....
wifi-ssid = "..."
wifi-password = "..."
....

HTTP authentication will come from these entries in `~/.drogue/config.toml`:

....
http-username = "..."
http-password = "..."
....

For Drogue Cloud, the username/password is stored in this form: `device_id@application`.

=== Running with plain TCP

You can configure the IP constant to point to any HTTP server to receive events, or you can use link:https://github.com/drogue-iot/drogue-cloud/[drogue cloud] locally. For simplicity, start a local HTTP server in python that echoes the HTTP payload back:

....
curl -s https://raw.githubusercontent.com/drogue-iot/drogue-device/main/apps/drogue-temperature/server.py | python3 
....

To run the firmware using a given chip:

....
DEFMT_LOG=info PROBE_RUN_CHIP=STM32L4S5VI cargo run --release --features b-l4s5i-iot01a,debug --no-default-features
....

If you have the B-475E-IOT01A board, use the following parameters:

....
DEFMT_LOG=info PROBE_RUN_CHIP=STM32L475VG cargo run --release --features b-l475e-iot01a,debug --no-default-features
....

== Running with TLS

When the `tls` flag is enabled, the example is configured to use the Drogue Cloud sandbox. To use this example with your own Drogue Cloud instance, you need to edit the HOST and PORT constants in `src/main.rs`.

To run the firmware using a given chip:

....
DEFMT_LOG=info PROBE_RUN_CHIP=STM32L4S5VI cargo run --release --features b-l4s5i-iot01a,tls,debug --no-default-features
....

If you have the B-475E-IOT01A board, use the following parameters:

....
DEFMT_LOG=info PROBE_RUN_CHIP=STM32L475VG cargo run --release --features b-l475e-iot01a,tls,debug --no-default-features
....

Once flashed, the device will reset and attempt to join the WiFi network. If successful, it will print a message to the RTT log. You can then press the blue/user button on the board to send a test message from the device.

== Troubleshooting

If you’re experiencing problems, try setting the `VID:PID` values to that of your probe (you can find that from lsusb once your board is powered).

....
<ENV> cargo run <ARGS> -- --probe <VID>:<PID>
....
