[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "nucleo-h743zi_esp8266"
version = "0.1.0"
resolver = "2"
description = "STM32 Nucleo-H743 + ESP8266 WiFi adapter"
keywords = ["networking", "wifi", "esp8266", "stm32", "stm32h7"]

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

embedded-hal = { version = "0.2.4", features = ["unproven"] }
drogue-device = { path = "../../../../device", features = ["wifi+esp8266", "defmt", "defmt-trace"], default-features = false }
drogue-tls = { git = "https://github.com/drogue-iot/drogue-tls.git", rev = "35033c66bfc622e6e5b271143c45cee1dbc2f0f8", default-features = false, features = ["async", "defmt"], optional = true}
#drogue-tls = {path = "../../../../../drogue-tls", default-features = false, features = ["async", "defmt"], optional = true}
wifi-app = { path = "../../../../apps/wifi", features = ["defmt"]}
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = "0.6"
void = { version = "1", default-features = false }
rand_core = { version = "0.6", default-features = false }
cfg-if = "1.0.0"

embassy = { version = "0.1.0", default-features = false, features = ["defmt"] }
embassy-stm32 = { version = "0.1.0", default-features = false, features = ["stm32h743zi", "defmt", "defmt-info", "memory-x", "time-driver-tim2"] }

[features]
default = []
tls = ["drogue-tls", "drogue-tls/defmt", "drogue-device/tls"]
