= A basic application

So you've got one of the xref:examples.adoc[examples] running, but what now? Let's go through a simple application for the BBC:microbit to understand it better.

The application is a simple game: As a cursor traverses the LED matrix, use the button to toggle the 'set' state of each individual LED. Once all LEDs are lit, you win!

== Main

The full example can be found link:https://github.com/drogue-iot/drogue-device/tree/main/docs/modules/ROOT/examples/basic[here].

=== Rust Nightly

The first thing you'll notice is a few declarations stating that the application requires some nightly features:

[source,rust]
----
include::example$basic/src/main.rs[lines="1..5"]
----

=== Dealing with errors

Then, what follows are some declarations on how to deal with panics and faults. During development, a good practice is to rely on `defmt-rtt` and `panic-probe` to print diagnostics to the terminal:

[source,rust]
----
include::example$basic/src/main.rs[lines="7..8"]
----

== Main

The main entry point is defined using the `#[embassy::main]` macro. The entry point is also required to take a `Spawner` argument.

The `Spawner` is the way the main application spawns tasks and actors.

For some boards, a Board Support Package (BSP) helps locating peripherals with a board-specific name. The board simply helps configuring the peripherals and giving them a name that maps to your particular board. In our case, we can use the `Microbit` board.

We'll model the game as an async task called `run_game`, which we will spawn from `main`. We then wait for button events and pass that to the game using a `Channel`.

[source,rust]
----
include::example$basic/src/main.rs[lines="18..47"]
----

We define a `GameMessage` type that our task will expect to be notified of whenever the button is pressed. The `DynamicReceiver` type is a handle that you can use to receive events that get sent to a `Channel`.

== Game logic

Having the setup code out of the way, we can now focus on our application. The game logic can be described as follows:

.Game logic
. Define a set of coordinates in a 5x5 matrix
. Initialize cursor at (0, 0)
. Initialize coordinates as not being visited
. While not all coordinates visited
.. Lit the LED at the cursor coordinate
.. Wait for a GameMessage to arrive within a timeout
.. If a GameMessage::Toggle arrived, toggle the visited status at the cursor coordinate
.. Unlit the LED at the cursor coordinate, if not visited
.. Update cursor

The game logic is implemented here:

[source,rust,indent=0]
----
include::example$basic/src/main.rs[lines="48..-1"]
----

The LedMatrix has an `on` and `off` method to toggle the LED at a given coordinate. In order to render the current LedMatrix state, we need to call a render function at the desired refresh interval. The "outer" loop does just that until one of the 'game logic' futures are completing.

The `events.recv()` is an async funtion that completes when an event have been received (i.e. button has been pressed).

The `Timer` type can be used to asynchronously wait for an event. The `select` function can be used to "race" two async functions for completion.

Therefore, the outer select races the rending loop and the `events.recv()` and timer, whereas they are raced against eachother. If there is an event or timeout, we update the game state.


=== Summary

We've gone through a basic application written for the BBC micro:bit. We've created an async task to drive the game logic, and wired it together with a channel receiving events from the main task.
