= Examples

There are several examples for different chips to show how drogue device can be used. The examples are grouped by what sort
of connectivity they use, and also by some capabilities such as over the air updates.

All examples can be debugged using `cargo run`, which often require the `probe-run` tool (`cargo install probe-run`) to flash the program.

You can also use the `cargo-flash` tool (`cargo install cargo-flash`) to run the examples in "production" mode.

== Configuration

All examples requiring user credentials, e.g. WiFi, HTTP, LoRaWAN, will expect them in the top-level keys of `.drogue/config.toml`. Similar to how link:https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure[cargo
configuration works], the build script for each example looks for that configuration file in the manifest directory, all of its parent directories, and finally in `$HOME/.drogue/config.toml`. If a key is specified in multiple config files, the values will be merged, with the value in the deeper directory taking precedence over its parents, the home directory having the lowest priority.

Credentials for your local WiFi network:
....
wifi-ssid = "..."
wifi-password = "..."
....

HTTP authentication:
....
http-username = "..."
http-password = "..."
....

_Over The Air Authentication_ (OTAA) credentials for LoRaWAN:
....
"dev-eui" = "..."
"app-eui" = "..."
"app-key" = "..."
....

These values will be read during compilation and stored in the executable.

== WiFi examples

Examples that demonstrates network connectivity using WiFi.

include::examples_wifi.adoc[]

== Ethernet examples

Examples that demonstrates network connectivity using Ethernet.

include::examples_ethernet.adoc[]

== LoRaWAN examples

Examples that demonstrates network connectivity using LoRaWAN.

include::examples_lorawan.adoc[]

== Bluetooth examples

Examples that demonstrates using Bluetooth Low Energy (BLE) or Bluetooth Mesh (BT Mesh).

include::examples_ble.adoc[]

== Std examples

Examples that runs out of the box on operating systems.

include::examples_std.adoc[]

== Over The Air (OTA) examples

Examples that have the capability of updating themselves over the air.

NOTE: These examples require a bootloader to be flashed, which you can find alongside the example folder.

include::examples_ota.adoc[]
