[package]
name = "rak811"
version = "0.1.0"
edition = "2021"
description = "An embassy-based boards support package (BSP) for the RAK811 board"

[workspace]

[dependencies]
embassy-stm32 = { version = "0.1.0", default-features = false, features = ["exti", "unstable-traits", "nightly", "stm32l151cb-a", "memory-x", "time-driver-any", "unstable-pac"] }
embassy-time = { version = "0.1.0", default-features = false }
embassy-lora = { version = "0.1.0", default-features = false, features = ["sx127x", "time"] }
static_cell = "1"
cortex-m = "0.7"
lorawan-device = { version = "0.8", default-features = false, features = ["async"] }
lorawan = { version = "0.7.1", default-features = false, features = ["default-crypto"] }
rand = { version = "0.8.4", default-features = false, features = ["small_rng"] }

[features]
defmt = [
    "embassy-lora/defmt",
    "embassy-stm32/defmt",
    "lorawan-device/defmt",
]

[patch.crates-io]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "645fb66a5122bdc8180e0e65d076ca103431a426" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "645fb66a5122bdc8180e0e65d076ca103431a426" }
embassy-lora = { git = "https://github.com/embassy-rs/embassy.git", rev = "645fb66a5122bdc8180e0e65d076ca103431a426" }
