[unstable]
build-std = ["core"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",

    # Code-size optimizations.
    "-Z", "trap-unreachable=no",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[build]
target = "thumbv7em-none-eabihf"
