= drogue-device examples

The examples are grouped by chip family, then board, then variant. I.e.

For instance, the example in `nrf52/microbit/esp8266` is for the `nRF52` chip family, using the `microbit` board,
with a variant that uses a `esp8266` WiFi module.

All example can be run using `cargo run`, which in some cases require the `probe-run` tool (`cargo
install probe-run`) to flash the program.

== Configuration

Any examples requiring user credentials, e.g. WiFi, HTTP, OTAA, will
expect them in the top-level keys of `.drogue/config.toml`. Similar to
how
link:https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure[cargo
configuration works], the build script for each example looks for that
configuration file in the manifest directory, all of its parent
directories, and finally in `$HOME/.drogue/config.toml`. If a key is
specified in multiple config files, the values will be merged, with
the value in the deeper directory taking precedence over its parents,
the home directory having the lowest priority.

Credentials for your local WiFi network:
....
wifi-ssid = "..."
wifi-password = "..."
....

HTTP authentication:
....
http-username = "..."
http-password = "..."
....

_Over The Air Authentication_ (OTAA) credentials:
....
"dev-eui" = "..."
"app-eui" = "..."
"app-key" = "..."
....

These values will be read during compilation and stored in the executable.
