[package]
name = "rp2040-pico-w"
version = "0.1.0"
edition = "2021"
description = "Raspberry Pi Pico W reporting sensor data using WiFi"
keywords = ["wifi", "rpi", "networking", "iot", "picow", "cloud"]

[workspace]

[dependencies]
cyw43 = { version = "0.1.0", features = ["defmt"] }
embassy-executor = { version = "0.1.0",  features = ["defmt", "integrated-timers"] }
embassy-time = { version = "0.1.0",  features = ["defmt", "defmt-timestamp-uptime"] }
embassy-usb-logger = "0.1.0"
embassy-rp = { version = "0.1.0",  features = ["defmt", "unstable-traits", "nightly", "unstable-pac", "time-driver"] }
embassy-net = { version = "0.1.0", features = ["defmt", "tcp", "dhcpv4", "medium-ethernet", "pool-16", "unstable-traits", "nightly"] }
drogue-device = { version = "0.1.0", default-features = false }
atomic-polyfill = "0.1.5"
static_cell = "1.0"

defmt = {version = "0.3", optional = true }
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }
reqwless = { version = "0.2", default-features = false, features = ["defmt"] }

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.0"
futures = { version = "0.3.17", default-features = false, features = ["async-await", "cfg-target-has-atomic", "unstable"] }
rand_core = { version = "0.6.2", default-features = false }

embedded-hal-1 = { package = "embedded-hal", version = "1.0.0-alpha.9" }
embedded-hal-async = { version = "0.1.0-alpha.3" }
embedded-io = { version = "0.3.0", features = ["async", "defmt"] }
heapless = "0.7.15"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.4", default-features = false, features = ["heapless"] }
embedded-tls = { version = "0.9.0", default-features = false, features = ["async", "defmt"]}
embedded-nal-async = "0.2.0"
rand = { version = "0.8.4", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
log = "0.4"

[features]
defmt = ["dep:defmt"]
default = ["defmt"]

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-boot = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-lora = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-net = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
embassy-usb-logger = { git = "https://github.com/embassy-rs/embassy", rev = "5c52d6c2172ba76267fd79b74f406fc74a50744d" }
cyw43 = { git = "https://github.com/embassy-rs/cyw43.git", rev = "8a81114baf4ffe12ec54e80e342f098c596177d1"}
drogue-device = { path = "../../../device" }

[profile.dev]
debug = 2
debug-assertions = true
opt-level = 1
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 'z'
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false
