== std-esp8266 drogue-device example

This example application runs out of the box on a PC with a ESP8266 breakout module flashed with AT firmware attached using a USB-to-Serial cable.

=== Prerequisites

==== Hardware

* USB to Serial cable
* ESP8266 module with AT-command firmware version 1.7.x or newer.

==== Software

* To build the example, you need to have link:https://rustup.rs/[Rust Nightly].
* The Drogue IoT service. See [drogue-cloud](https://github.com/drogue-iot/drogue-cloud) for how to run that, or use the [sandbox](https://sandbox.drogue.cloud).

=== Configuring

To use this example with your own Drogue IoT service, you need to edit the HOST and PORT constants in `src/main.rs`. 

To access your local WiFi network, the store the ssid in `config/wifi.ssid.txt` and pre-shared key in `config/wifi.password.txt`.

To access Drogue IoT Cloud, you must store the username and password in `config/drogue.username.txt`
and `config/drogue.password.txt`. The username is stored in this form: `device_id@application`.

=== Building

....
cargo build --release
....

Then run:

....
cargo run
....

The application will wait until the ESP8266 is reset, some breakout modules provide a reset button, others require you to power the ESP8266 separately from the serial cable in order to proberly reset.

Once reset, the application will connect to the WiFi access point and send a test message to Drogue IoT.