== stm32f401-esp8266 drogue-device example

This example application runs out of the box on the STM32 Nucleo-64.
It relies on a ESP8266 breakout module flashed with AT firmware. The
Nucleo communicates with the ESP8266 using USART.

==== Hardware

* STM32 Nucleo-64 STM32F401
* ESP8266 module with AT-command firmware version 1.7.x or newer.

==== Software

To build and flash the example, you need to have
https://rustup.rs/[Rust],
https://crates.io/crates/cargo-embed[cargo-embed] installed. In
pratice you can use whatever tool you want to flash the device, but
this guide will assume cargo-embed is used.

=== Configuring

To use this example, you need to edit the ENDPOINT and ENDPOINT_PORT variables in `src/main.rs`. You
also need to store your WiFi access point ssid in `config/wifi.ssid.txt` and pre-shared key in
`config/wifi.password.txt`.

=== Building

Make sure you have the correct target architecture supported in rust:

....
rustup target add thumbv7em-none-eabi
....

To build the firmware:

....
cargo build --release
....

=== Flashing

Flashing the firmware uses the configuration from the Embed.toml file,
which auto-detects the probe connected to your device. If you’re
experiencing problems, try setting the `usb_vid` and `usb_pid` values to
that of your probe (you can find that from lsusb once your board is
powered).

The following command will build and flash the firmware and open the
debugger console so you can see the console debug output.

....
cargo embed --release
....
