== microbit-rak811 drogue-device example

This example application runs out of the box on the BBC micro:bit v2.0.
It relies on a RAK811 LoRa shield to which it communicates over UART.

=== Prerequisites

==== Hardware

* BBC micro:bit v2.0
* RAK811 LoRa module with AT-firmware attached to UART

==== Software

To build and flash the example, you need to have
https://rustup.rs/[Rust],
https://crates.io/crates/cargo-embed[cargo-embed] installed. In pratice
you can use whatever tool you want to flash the device, but this guide
will assume cargo-embed is used.

=== Configuring

To use this example, you need to create the files `config/dev_eui.txt`, `config/app_eui.txt`, and
`config/app_key.txt` to configure the device EUI, application EUI, and application key for OTAA
configuration of your device.

=== Building

Make sure you have the correct target architecture supported in rust:

....
rustup target add thumbv7em-none-eabihf
....

To build the firmware:

....
cargo build --release
....

=== Flashing

Flashing the firmware uses the configuration from the Embed.toml file,
which auto-detects the probe connected to your device. If you’re
experiencing problems, try setting the `usb_vid` and `usb_pid` values to
that of your probe (you can find that from lsusb once your board is
powered).

The following command will build and flash the firmware and open the
debugger console so you can see the console debug output.

....
cargo embed --release
....
